language: node_js
services:
- docker
os:
- linux
node_js:
- node
install:
- npm install
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: zxjikBTnjXHoFm6xEn3ros3c7VnUHEjKtMcsR7rrRaQUzdrOBGn/zqeHJutpdyd+81bmHhr/XXg/UF4GfBCpQLUpT29ILAC7MmpQ8AoUfZJjBRBFJAoPGY+IMlBYvXFcGNmGjdANpYgNwQFif7eVE6QT5guU+5vSLoM5Fk3u/b0GFORP0WzRbrovLx8AuRSkjLyB+iNvWHpwPwZ0M65qB9ZnAhIWFUONbbK4Iv8ajW9w9KZ85Do9plXNGNfEKDDuNwi2h0tCbkl2uVHeMZXf/gWMH7WAVNZEeFcl7hSmuM88sKrXLjQ7tjIUGoDhIsrnCUBDb0sG0Q1mtRzQoX3Lboh0oFY4g1TuB1o67pVOe+1zlhL+CJ88z0kCdMq2Onz9jtwCTMNcldbo6B3OPpxu2kLnk0sTxvtZX9ETJtxxM7MYPXdOkt+i90FQwEUhcHKnhwzFNWMt15Jge9Xg5m0e1UFrP7qa82+0WtmZLjplZYlIKQzYSk2PATej8o82kTiwO1hZX/zCYWJ9TpnjCk4ymlIj9BvGZRX/G5kqb3C7EsLARcONleLPNKlI8P+n9/skV5Owkg2VVhsNykVlZB/lsS4MPJBL1aOfOJnD08fT2HZ1t6A41qVoLNOh6zdO2Bi+rxWf9thzEq0JimQNnGeXbpmxBcztJA3Q3I2X59S5DEg=
  - secure: PLfbwQZjETzytU6i7jNAeGeCZGyLhhqb6aY2w6FdqGXq9bf90K5hxP7rAEO5DBIj2Zx136U/RFsN3g7+663ci/fMgPHZB7GcEEAH3y2hqkkbLh8OaJLgGICguTp2GTChMCNxXoSa7gVV+XuwJunuW5ZCGap4vdpeIg5Bc3lvIBSLawxEg3bLY3m8ibLsMbOKJYCDMc67izRt/a83evF+O4ILMJiSJZwSyEEb8VRhpzxHB0Bj0qyfA5dmNc3G11stWAKPv1YKmeuJK7u9EDtEoCTHY1aRk028XjODUZlQ30+yhFPJVRk1eT/4Iq5Ai9H0bTN33KV92NljwVfP5g8d0tGSaVHp+t6LrR0cEPonIH8F/PNaQSWde2jE/8Iio5inNgRFagMpJ6ujqDB5Ko0lh8hpGi4nBA/ygwvymDXwnmBSZGXOxgI6Ndl52VEZgNEe7bufSysb+x/90Z5SblsEdaqZFaYRcKbI5DXNuWaiGEagv4W3SMbnISCICKAjNwV+S4wbLa+mRe7tQ4flQYgnKuD56O9fQPCiObR1Iip9jEdjbCXhS4BsjfBN2c5A2D95X1Kc6PnpziGYK9hs42oiY87Q4O3MGvas253Dy2ZRc694sTaIX9pbM0E1Yi2SyYWpVoQ9jLHGHoN2NsLe5RLlD3q6nkDGj2g5OMBVlC08iW0=
